name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: bench
          allow-softlinks: true
          python-version: ${{ matrix.python }}
          channels: conda-forge
          channel-priority: strict
          miniforge-version: latest
          use-only-tar-bz2: true
          use-mamba: true
      - uses: actions/checkout@v4
      - name: Build and test
        run: |
          pip install asv virtualenv
          asv machine --yes
          asv run --quick --dry-run
